### ISSUE TITLE
Check for broken links when sending pug/cat pics

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/eva#8]
Eva sometimes send broken links for pugs and cats when the command `pug bomb` or `cat bomb` is used.

**Comment by thealphadollar** [comment]
@icyflame  @DefCon-007  This requires changing the insides of a module we have directly used. I don't think should be done independently of the source.

I can file an issue in the main repo and do it for them, but I need to see a reproduction of the issue. If not, that means it has been fixed by the developers and the issue must be closed.
